gitlab:
  match:
    - '.gitlab'
    - '.gitlab-ci.yml'
  description: 'Relating to gitlab'

github:
  match:
    - '.github'
  description: 'Relating to github'

ci/cd:
  match:
    - 'ci/cd'
    - 'pipeline'
    - 'workflow'
    - 'dockerfile'
    - 'compose.yaml'
  description: ''

feat:
  match:
    - 'feat'
    - 'feature'
    - 'features'
    - 'enhancement'
  description: 'Feature or enhancement'

dotfiles:
  match:
    - '.gitlab-ci.yml'
    - '.gitignore'
    - '.gitattributes'
    - '.dockerignore'
  description: ''

question:
  match:
    - '?'
    - 'question'
    - 'please help'
    - 'help'
  description: ''

schedule:
  match:
    - 'schedule'
    - 'daily'
    - 'ci'
    - 'cd'
  description: ''

boss:
  match:
    - 'boss'
    - 'admin'
    - 'final-boss'
  description: ''
