#####################################################
# All Rights Reserved. 2020 - Present. (offensive-vk)
#####################################################
image: ubuntu

stages:
  - upload
  - refresh

upload:
  stage: upload
  script:
    - cat .github/secrets.json
    - echo "Checking out the complete repository..."
    - sleep 15
    - echo "Repository checked out successfully."
  artifacts:
    name: "offensive-vk"
    paths:
      - .
  only:
    - schedule

refresh:
  stage: refresh
  script:
    - sleep 10
    - echo "Compressing the repository into a ZIP file..." | base64
    - sleep 5
    - apt update; apt install zip tar neofetch -y
    - neofetch
    - echo "The repository has been compressed verified."
    - sleep 10
  artifacts:
    name: "offensive-vk-zip"
    paths:
      - offensive-vk.zip
  only:
    - schedule