name: 📌 Automated Issue Pinner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  pin-latest-issues:
    runs-on: ubuntu-latest
    name: Find and Pin Issues
    steps:
      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Unpin All Previously Pinned Issues
        run: |
          PINNED_ISSUES=$(gh issue list --repo "${{ github.repository }}" --state open --json number,isPinned | jq -r '.[] | select(.isPinned) | .number')

          for ISSUE_NUMBER in $PINNED_ISSUES; do
            gh issue unpin $ISSUE_NUMBER --repo "${{ github.repository }}"
          done

      - name: Get Last 3 Open Issues and Pin Them
        continue-on-error: true
        run: |
          ISSUES=$(gh issue list --repo "${{ github.repository }}" --state open --limit 3 --json number --jq '.[].number')

          for ISSUE_NUMBER in $ISSUES; do
            gh issue pin $ISSUE_NUMBER --repo "${{ github.repository }}"
          done
