name: 📝 Daily Code Snippet

on:
  schedule:
    - cron: '15 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:
jobs:
  code-snippet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Random Code Snippet
        run: |
          snippets=(
            "printf('Hello, World !');"
            "std::cout << "Hello, World!" << std::endl;"
            "print('Hello, World!')"
            "console.log('Hello, World!');"
            "echo 'Hello, World!'"
            "fmt.Println('Hello, World!')"
            "puts 'Hello, World!'\n"
            "System.out.printf('Hello, World.');"
          )
          random_snippet=${snippets[$RANDOM % ${#snippets[@]}]}
          touch .github/CODE_SNIPPET.md
          echo -e "$random_snippet" > .github/CODE_SNIPPET.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "npm-run-test"
          git config --global user.email "node_modules@hotmail.com"
          git fetch && git pull
          git add .
          git commit -m ":rabbit2: Updated Code Snippet of the Day.

          Signed-off-by: Hamster [bot] <node_modules@hotmail.com>
          Co-Authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          git push
