name: 🦅 Mirror Sync

on:
  push:
    branches: ['**']
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Ping Repo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: offensive-vk/auto-repo-sync@master
        with:
          target-url: ${{ secrets.TARGET_URL }}
          target-username: ${{ secrets.TARGET_USER }}
          target-token: ${{ secrets.TARGET_TOKEN }}